# Generated by Django 5.2.8 on 2026-02-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockcrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='pen_location',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='purchase_price',
        ),
    ]
