# Generated by Django 5.2.8 on 2026-03-13 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestockcrud', '0002_remove_livestock_pen_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('comprehensive', 'Comprehensive')], max_length=20, unique=True)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('covers_death', models.BooleanField(default=True)),
                ('covers_theft', models.BooleanField(default=False)),
                ('covers_disease', models.BooleanField(default=False)),
                ('covers_accident', models.BooleanField(default=False)),
                ('covers_natural_disaster', models.BooleanField(default=False)),
                ('waiting_period_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['coverage_amount'],
                'indexes': [models.Index(fields=['plan_type'], name='insurance_i_plan_ty_f62490_idx'), models.Index(fields=['is_active'], name='insurance_i_is_acti_136809_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_enrollments', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_enrollments', to='livestockcrud.livestock')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='insurance.insuranceplan')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('Death', 'Death'), ('Theft', 'Theft'), ('Disease', 'Disease'), ('Accident', 'Accident'), ('Natural Disaster', 'Natural Disaster'), ('Other', 'Other')], max_length=50)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Submitted', max_length=30)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='insurance/claims/')),
                ('vet_notes', models.TextField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claims', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'status'], name='insurance_c_farmer__245a9f_idx'), models.Index(fields=['veterinarian', 'status'], name='insurance_c_veterin_9db3bc_idx'), models.Index(fields=['status'], name='insurance_c_status_5572b5_idx'), models.Index(fields=['incident_date'], name='insurance_c_inciden_a6e86e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['farmer', 'status'], name='insurance_e_farmer__274157_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['livestock'], name='insurance_e_livesto_b5d00b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['start_date', 'end_date'], name='insurance_e_start_d_c4097a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('livestock', 'plan', 'start_date')},
        ),
    ]
