# Generated by Django 5.1.6 on 2026-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='medical_history',
            field=models.FileField(blank=True, null=True, upload_to='insurance/claims/medical/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='vaccination_history',
            field=models.FileField(blank=True, null=True, upload_to='insurance/claims/vaccination/'),
        ),
    ]
