# Generated by Django 5.1.6 on 2026-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_remove_vet_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='insurance_c_veterin_9db3bc_idx',
        ),
        migrations.AlterField(
            model_name='claim',
            name='incident_image',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/claims/images/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Submitted', max_length=30),
        ),
    ]
