# Generated by Django 5.1.6 on 2026-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_remove_claim_insurance_c_veterin_9db3bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/enrollments/payment_proofs/'),
        ),
    ]
