# Generated by Django 5.2.8 on 2026-03-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestockcrud', '0002_remove_livestock_pen_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200)),
                ('diagnosis', models.TextField()),
                ('vet_name', models.CharField(max_length=100)),
                ('treatment_date', models.DateField()),
                ('next_treatment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='treatment_docs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='livestockcrud.livestock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.PositiveIntegerField(choices=[(1, 'Once'), (2, 'Twice'), (3, 'Three times')])),
                ('duration', models.PositiveIntegerField(default=3, help_text='Days')),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('exact', 'Exact Times')], default='interval', max_length=10)),
                ('start_time', models.TimeField()),
                ('interval_hours', models.PositiveIntegerField(blank=True, default=8, null=True)),
                ('exact_times', models.JSONField(blank=True, default=list, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medical.treatment')),
            ],
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['user', 'status'], name='medical_tre_user_id_0f1937_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['user', 'next_treatment_date'], name='medical_tre_user_id_6e0540_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['livestock', 'status'], name='medical_tre_livesto_dd4754_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['treatment', 'name'], name='medical_med_treatme_6991ef_idx'),
        ),
    ]
