import axios from 'axios';

// Base URL for livestock API
const API_BASE_URL = 'http://localhost:8000/api/v1/livestock';

// Create axios instance with default config
const livestockApi = axios.create({
  baseURL: API_BASE_URL,
});

// Add request interceptor to include JWT token
livestockApi.interceptors.request.use(
  (config) => {
    // Prioritize sessionStorage (tab-specific) over localStorage (shared across tabs)
    const token = sessionStorage.getItem('token') || localStorage.getItem('token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Add response interceptor to handle 401 errors
livestockApi.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      // Token expired or invalid - redirect to login
      localStorage.removeItem('token');
      window.location.href = '/login';
    }
    return Promise.reject(error);
  }
);

// ============= LIVESTOCK CRUD OPERATIONS =============

// Get all livestock for the authenticated user
export const getAllLivestock = async (params = {}) => {
  try {
    console.log('[API] Fetching all livestock...');
    const response = await livestockApi.get('/livestock/', { params });
    console.log('[API] Livestock response status:', response.status);
    console.log('[API] Livestock response data:', response.data);
    console.log('[API] Response data type:', typeof response.data);
    console.log('[API] Response is array:', Array.isArray(response.data));
    
    // Handle paginated response
    if (response.data.results) {
      console.log('[API] Paginated response detected');
      console.log('[API] Results:', response.data.results);
      console.log('[API] Results length:', response.data.results.length);
    }
    
    return { success: true, data: response.data };
  } catch (error) {
    console.error('[API] Get livestock error:', error);
    console.error('[API] Error response:', error.response?.data);
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to fetch livestock.' }
    };
  }
};

// Preview next tag ID for the current user
export const previewNextTagId = async () => {
  try {
    const response = await livestockApi.get('/livestock/preview-tag-id/');
    return { success: true, data: response.data };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to preview tag ID.' }
    };
  }
};

// Get single livestock by ID
export const getLivestockById = async (id) => {
  try {
    const response = await livestockApi.get(`/livestock/${id}/`);
    return { success: true, data: response.data };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to fetch livestock details.' }
    };
  }
};

// Create new livestock
export const createLivestock = async (formData) => {
  try {
    console.log('[API] Creating livestock with formData:', formData);
    const data = new FormData();
    
    // Don't append tag_id - it will be auto-generated by backend
    
    // Handle species - if it's a string (new species), create it first
    let speciesId = formData.species;
    console.log('[API] Species value:', speciesId, 'Type:', typeof speciesId);
    if (typeof formData.species === 'string') {
      const speciesResult = await createSpecies(formData.species);
      if (speciesResult.success) {
        speciesId = speciesResult.data.id;
      } else {
        return { success: false, error: { message: 'Failed to create species.' } };
      }
    }
    
    // Handle breed - if it's a string (new breed), create it first
    let breedId = formData.breed;
    console.log('[API] Breed value:', breedId, 'Type:', typeof breedId);
    if (typeof formData.breed === 'string') {
      const breedResult = await createBreed(formData.breed, speciesId);
      if (breedResult.success) {
        breedId = breedResult.data.id;
      } else {
        return { success: false, error: { message: 'Failed to create breed.' } };
      }
    }
    
    // Append all required fields
    console.log('[API] Appending species:', speciesId);
    console.log('[API] Appending breed:', breedId);
    console.log('[API] Appending date_of_birth:', formData.date_of_birth);
    console.log('[API] Appending gender:', formData.gender);
    
    data.append('species', speciesId);
    data.append('breed', breedId);
    data.append('date_of_birth', formData.date_of_birth);
    data.append('gender', formData.gender);
    
    // Append optional fields if they exist
    if (formData.color) data.append('color', formData.color);
    if (formData.weight) data.append('weight', formData.weight);
    if (formData.health_status) data.append('health_status', formData.health_status);
    if (formData.remarks) data.append('remarks', formData.remarks);
    
    // Append image if exists
    if (formData.image && formData.image instanceof File) {
      console.log('[API] Appending image:', formData.image.name);
      data.append('image', formData.image);
    }
    
    console.log('[API] Sending FormData to backend...');
    const response = await livestockApi.post('/livestock/', data, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    });
    console.log('[API] Create livestock success:', response.data);
    return { success: true, data: response.data };
  } catch (error) {
    console.error('[API] Create livestock error:', error);
    console.error('[API] Error response:', error.response?.data);
    console.error('[API] Error status:', error.response?.status);
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to create livestock.' }
    };
  }
};

// Update existing livestock
export const updateLivestock = async (id, formData) => {
  try {
    const data = new FormData();
    
    // Append all required fields
    data.append('tag_id', formData.tag_id);
    data.append('species', formData.species);
    data.append('breed', formData.breed);
    data.append('date_of_birth', formData.date_of_birth);
    data.append('gender', formData.gender);
    
    // Append optional fields if they exist
    if (formData.color) data.append('color', formData.color);
    if (formData.weight) data.append('weight', formData.weight);
    if (formData.health_status) data.append('health_status', formData.health_status);
    if (formData.remarks) data.append('remarks', formData.remarks);
    
    // Append image if exists and is a new file
    if (formData.image && formData.image instanceof File) {
      data.append('image', formData.image);
    }
    
    const response = await livestockApi.put(`/livestock/${id}/`, data, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    });
    return { success: true, data: response.data };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to update livestock.' }
    };
  }
};

// Delete livestock
export const deleteLivestock = async (id) => {
  try {
    await livestockApi.delete(`/livestock/${id}/`);
    return { success: true };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to delete livestock.' }
    };
  }
};

// ============= SPECIES OPERATIONS =============

// Get all species
export const getAllSpecies = async () => {
  try {
    const response = await livestockApi.get('/species/');
    console.log('[API] Species raw response:', response.data);
    console.log('[API] Species response type:', typeof response.data);
    console.log('[API] Species is array:', Array.isArray(response.data));
    
    // Handle paginated response - extract results array
    const data = response.data.results || response.data;
    console.log('[API] Species final data:', data);
    console.log('[API] Species final data is array:', Array.isArray(data));
    
    return { success: true, data: data };
  } catch (error) {
    console.error('[API] Species error:', error);
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to fetch species.' }
    };
  }
};

// Create new species
export const createSpecies = async (name) => {
  try {
    const response = await livestockApi.post('/species/', { name });
    return { success: true, data: response.data };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to create species.' }
    };
  }
};

// ============= BREED OPERATIONS =============

// Get all breeds (optionally filter by species)
export const getAllBreeds = async (speciesId = null) => {
  try {
    const params = speciesId ? { species: speciesId } : {};
    const response = await livestockApi.get('/breeds/', { params });
    console.log('[API] Breeds raw response:', response.data);
    console.log('[API] Breeds response type:', typeof response.data);
    console.log('[API] Breeds is array:', Array.isArray(response.data));
    
    // Handle paginated response - extract results array
    const data = response.data.results || response.data;
    console.log('[API] Breeds final data:', data);
    console.log('[API] Breeds final data is array:', Array.isArray(data));
    
    return { success: true, data: data };
  } catch (error) {
    console.error('[API] Breeds error:', error);
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to fetch breeds.' }
    };
  }
};

// Create new breed
export const createBreed = async (name, speciesId) => {
  try {
    const response = await livestockApi.post('/breeds/', {
      name,
      species: speciesId
    });
    return { success: true, data: response.data };
  } catch (error) {
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to create breed.' }
    };
  }
};

export default livestockApi;


/**
 * Get livestock for a specific farmer (by username)
 * For vets to view a farmer's animals
 */
export const getLivestockByFarmer = async (username) => {
  try {
    console.log('[API] Fetching livestock for farmer:', username);
    const response = await livestockApi.get('/livestock/', {
      params: { owner: username }
    });
    console.log('[API] Farmer livestock response:', response.data);
    
    return { success: true, data: response.data };
  } catch (error) {
    console.error('[API] Get farmer livestock error:', error);
    return {
      success: false,
      error: error.response?.data || { message: 'Failed to fetch farmer livestock.' }
    };
  }
};
