# Generated by Django 5.2.8 on 2026-03-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for the appointment')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vet_notes', models.TextField(blank=True, help_text='Notes from veterinarian', null=True)),
                ('farmer', models.ForeignKey(help_text='Farmer who requested the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='farmer_appointments', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(help_text='Veterinarian assigned to the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'status'], name='appointment_farmer__55a4c1_idx'), models.Index(fields=['veterinarian', 'status'], name='appointment_veterin_9874bd_idx'), models.Index(fields=['preferred_date'], name='appointment_preferr_206def_idx')],
            },
        ),
    ]
