# Generated by Django 5.1.6 on 2026-04-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for this appointment (if applicable)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Payment record for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed')], default='not_required', help_text='Payment status for this appointment', max_length=20),
        ),
    ]
