# Generated by Django 5.2.8 on 2026-05-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointment_fee_appointment_payment_and_more'),
        ('livestockcrud', '0002_remove_livestock_pen_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='livestock',
            field=models.ForeignKey(blank=True, help_text='The specific livestock animal for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='livestockcrud.livestock'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='animal_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
