# Generated by Django 5.2.8 on 2026-03-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestockcrud', '0002_remove_livestock_pen_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for the transfer')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Receiver Approved', 'Receiver Approved'), ('Admin Approved', 'Admin Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('receiver_notes', models.TextField(blank=True, help_text='Notes from receiver', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting documents for the transfer', null=True, upload_to='transfers/documents/')),
                ('admin_reviewer', models.ForeignKey(blank=True, help_text='Admin who reviewed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(help_text='Livestock being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='livestockcrud.livestock')),
                ('receiver', models.ForeignKey(help_text='New owner receiving the livestock', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='Current owner initiating the transfer', on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='profileTran_sender__b20e5e_idx'), models.Index(fields=['receiver', 'status'], name='profileTran_receive_c3785f_idx'), models.Index(fields=['status'], name='profileTran_status_5e3fd9_idx'), models.Index(fields=['livestock'], name='profileTran_livesto_19eacc_idx'), models.Index(fields=['created_at'], name='profileTran_created_83c8ee_idx')],
            },
        ),
    ]
