# Generated by Django 5.2.8 on 2025-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='farm_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
