# Generated by Django 5.1.6 on 2026-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('appointment_card', 'Appointment Card')], default='text', max_length=20),
        ),
    ]
