# Generated by Django 5.2.8 on 2026-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default consultation fee in NPR (vet only).', max_digits=10, null=True),
        ),
    ]
