# Generated by Django 5.1.6 on 2026-04-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('account', 'Account Verification'), ('appointment', 'Appointment'), ('transfer', 'Profile Transfer'), ('insurance', 'Insurance'), ('medical', 'Medical Record'), ('vaccination', 'Vaccination'), ('message', 'Message'), ('friend', 'Friend Request'), ('system', 'System')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title/headline', max_length=255)),
                ('message', models.TextField(help_text='Notification message body')),
                ('link', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('data', models.JSONField(blank=True, help_text='Additional metadata for the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
